# .github/workflows/ci-pr.yml

name: PlanetScale CI/CD

env:
  PLANETSCALE_ORG_NAME: ${{ secrets.PLANETSCALE_ORG_NAME }}
  PLANETSCALE_DB_NAME: ${{ secrets.PLANETSCALE_DB_NAME }}
  PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
  PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - main

jobs:
  # deploy updated database with main
  deploy_changes:
    name: Deploy PlanetScale Dev Branch to Main
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.head.ref, 'db/') && github.event.pull_request.merged == true
    steps:
      - name: checkout
        uses: actions/checkout@v3

      # creating deploy request
      - name: Create a deploy request
        uses: planetscale/create-deploy-request-action@v1
        id: create_deploy_request
        with:
          org_name: ${{ secrets.PLANETSCALE_ORG_NAME }}
          database_name: ${{ secrets.PLANETSCALE_DB_NAME }}
          branch_name: dev-branch
          deploy_to: main

      - name: Get the deploy request number
        run: |
          echo "Deploy request number: ${{ steps.create_deploy_request.outputs.number }}"

      # deploying request
      - name: Deploy a deploy request
        uses: planetscale/deploy-deploy-request-action@v1
        with:
          org_name: ${{ secrets.PLANETSCALE_ORG_NAME }}
          database_name: ${{ secrets.PLANETSCALE_DB_NAME }}
          number: ${{ steps.create_deploy_request.outputs.number }}
