name: Prisma Schema Validation
on:
  pull_request:
    branches: ["main"]
    paths: ["prisma/schema.prisma"]
    types: [opened, synchronize, closed]

jobs:
  validate:
    name: Validate prisma.schema
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'db/**')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Prisma validation fails if it cannot load env vars
      - name: Create dummy .env file
        run: echo "DATABASE_URL=mongodb+srv://test:test@localhost" > .env

      - name: Run schema validator
        uses: elijaholmos/prisma-schema-validate@v1
        with:
          # All inputs are optional - see Configuration section below
          version: latest # If empty, pulls from package.json
          schema: prisma/schema.prisma
