name: Remove Tests on Approval

on:
  # pull_request_review:
  #   types: [submitted]
  pull_request:
    types: [closed]

jobs:
  approved:
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: "."

          remove: "--cached -r '*.test.ts'"

          author_name: ${{github.event.pull_request.user.login}}

          author_email: ${{github.event.pull_request.user.email}}

          commit: --signoff

          default_author: github_actor

          fetch: false

          message: "Test removed from CI pipeline"
          pathspec_error_handling: ignore

          pull: "--rebase --autostash"
          push: true
