name: Remove Tests on Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  remove-test-files:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Git config
        run: |
          git config --local user.email "yonaries.dev@gmail.com"
          git config --local user.name "yonaries"

      - name: Remove test files
        run: git rm -r '*.test.ts'

      - name: Stage changes
        run: git add .

      - name: Commit changes
        run: git commit -m "CI(pipeline) - Remove test files"

      - name: Git pull
        run: git pull origin ${{ github.event.pull_request.head.ref }} --rebase --autostash

      - name: Push changes
        run: git push origin HEAD:${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GTH_TOKEN }}
