name: Remove Tests on Approval

on:
  # pull_request_review:
  #   types: [submitted]
  pull_request:
    types: [closed]

jobs:
  approved:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Git add remote
        run: git remote add pipeline https://github.com/yonaries/jegool-backend.git

      - name: Git fetch
        run: git fetch pipeline

      - name: Git checkout
        run: git checkout pipeline/${{ github.event.pull_request.head.ref }}

      - name: Git pull
        run: git pull pipeline ${{ github.event.pull_request.head.ref }} --rebase --autostash

      - name: Remove tests
        run: git rm -r '*.test.ts'

      - name: Add, commit and push
        run: |
          git config --local user.email "
          git config --local user.name "
          git add .
          git commit -m "Test removed from CI pipeline" --signoff
          git push pipeline ${{ github.event.pull_request.head.ref }}

      # - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      #   with:
      #     add: "."

      #     remove: "--cached -r '*.test.ts'"

      #     author_name: ${{github.event.pull_request.user.login}}

      #     author_email: ${{github.event.pull_request.user.email}}

      #     commit: --signoff

      #     default_author: github_actor

      #     fetch: false

      #     message: "Test removed from CI pipeline"
      #     pathspec_error_handling: ignore

      #     push: "git push origin ${{ github.event.pull_request.head.ref }}"
