name: Remove Tests on Approval

on:
  # pull_request_review:
  #   types: [submitted]
  pull_request:
    types: [closed]

jobs:
  approved:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        # with:
        # persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        # fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Remove Tests
        run: npm run remove:test

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: "."

          remove: "--cached -r '*.test.ts'"

          author_name: ${{github.event.pull_request.user.login}}

          author_email: ${{github.event.pull_request.user.email}}

          commit: --signoff

          default_author: github_actor

          fetch: false

          message: "Test removed from CI pipeline"
          pathspec_error_handling: ignore

          pull: "git pull origin ${{ github.event.pull_request.head.ref }} --rebase --autostash"
          push: true

        # - name: Remove Tests
        #   run: |
        #     find . -name '*.test.js' -delete
        #     git add .

        # - name: Commit & Push changes
        #   uses: actions-js/push@master
        #   with:
        #     github_token: ${{ secrets.GITHUB_TOKEN }}
